Karakteristik data, Deskripsi/gambaran dari datanya.
Berkutat di data yang ada/dikasih aja, ga ada konsep probabilitas.

Jika skew = median, karena kita gamau datanya di representasikan sama data yang gede banget

In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [2]:
x = [8.0, 1, 2.5, 4, 28.0]
x_with_nan = [8.0, 1, 2.5, math.nan, 4, 28.0]
print(x)
print(x_with_nan)

[8.0, 1, 2.5, 4, 28.0]
[8.0, 1, 2.5, nan, 4, 28.0]


In [8]:
y, y_with_nan =np.array(x), np.array(x_with_nan)
z, z_with_nan =pd.Series(x), pd.Series(x_with_nan)

### Measures of Centran Tendency

Measures of central tendency menunjukkan nilai tengah atau pusat dari kumpulan data. Berikut merupakan cara mengidentifikasi dan menghitung measures of central tendency: 

#### Mean/Average

rata-rata aritmatika dari semua elemen kumpulan data

In [18]:
# without packages
mean_python = sum(x)/len(x)
print(mean_python)

8.7


In [19]:
# with statistics
mean_stat = statistics.mean(x)
print(mean_stat)

8.7


Kita juga dapat menghitung mean walaupun datanya terdapat NaN hanya saja tidak disarankan karena sebelum memasuki tahap ini seharusnya data kita telah bersih dari missing value

In [20]:
# with statistics
mean_ = statistics.mean(x_with_nan)
print(mean_)

nan


In [24]:
# with numpy
print(np.mean(y_with_nan))
print(y_with_nan.mean())

nan
nan


In [25]:
# with numpy
np.nanmean(y_with_nan)

8.7

In [26]:
# # with pandas
z.mean()

8.7

In [27]:
z_with_nan.mean()

8.7

#### Weighted Mean

Generalisasi dari rata-rata aritmatika yang memungkinkan kita untuk menentukan kontribusi relatif dari setiap titik data ke hasil. Mengalikan setiap titik data dengan bobot yang sesuai, menjumlahkan semua produk, dan membagi jumlah yang diperoleh dengan jumlah bobot:

In [28]:
x = [8.0, 1, 2.5, 4, 28.0]
w = [0.1, 0.2, 0.3, 0.25, 0.15]

In [35]:
weighted_mean = sum([x[idx]*w[idx] for idx in range(0,len(x))])/sum(w)
print(weighted_mean)

weighted_mean_2 = sum([val_x*val_w for val_x, val_w in zip(x,w)])
print(weighted_mean_2)

6.95
6.95


In [36]:
y, z, w = np.array(x), pd.Series(x), np.array(w)

In [37]:
# with numpy
wmean = np.average(y, weights=w)
print(wmean)

wmean = np.average(z, weights=w)
print(wmean)

6.95
6.95


#### Harmonic Mean

Harmonic Mean: rata-rata kebalikan dari rata-rata aritmatika. Harmonic mean dihitung dengan membagi banyaknya nilai di kumpulan data dengan jumlah kebalikan (1 / x_i) dari setiap nilai dalam kumpulan data.  Harmonic mean biasa digunakan pada beberapa kasus data misalnya data kecepatan, rasio atau tarif. Ini adalah ukuran yang paling tepat untuk rasio dan tarif karena ini menyamakan bobot setiap titik data. Misalnya, mean aritmatika memberi bobot yang tinggi pada titik data yang besar, sedangkan mean geometrik memberikan bobot yang lebih rendah ke titik data yang lebih kecil (livingeconomyadvisors).

In [38]:
# with built-in function python
hmean = len(x) / sum(1 / item for item in x)
hmean

2.7613412228796843

In [39]:
# with statistics
statistics.harmonic_mean(x)

2.7613412228796843

In [42]:
# with scipy.stats
print(scipy.stats.hmean(x))
print(scipy.stats.hmean(y))
print(scipy.stats.hmean(z))

2.7613412228796843
2.7613412228796843
2.7613412228796843


10 km pertama -> 60 km/h <br>
10 km kedua -> 20 km/h <br>
harmonic mean? aritmatika mean?

In [106]:
(60+20)/2 # with arithmetic mean

40.0

In [107]:
2/((1/60)+(1/20)) # with formula harmonic mean

30.0

10 km pertama => 1/6 jam <br>
10 km kedua => 1/2 jam <br>

20 km dan (1/6+1/2)jam => 20 km dan 2/3 jam  <br>
v = s/t = 20 km / (2/3) jam = 30 km/jam <br>

Oleh karena itu kasus kecepatan seperti ini menggunakan harmonic mean

Kasus lain : <br>
Pompa A : dapat mengisi 1/4 kolam renang dalam 1 jam <br>
Pompa B : dapat mengisi 1/6 kolam renang dalam 1 jam <br>
Pompa C : dapat mengisi 1/3 kolam renang dalam 1 jam <br>

Jika digunakan ketiganya berapa lama waktu yang dibutuhkan untuk mengisi 1 kolam renang|

In [109]:
(1/4)+(1/6)+(1/3) # dalam 1 jam sudah terisi 3/4 kolam renang

0.75

1/x = 0.75/1 <br>
0.75x = 1 <br>
x = 1/0.75 <br>

In [111]:
1/0.75 # dibutuhkan 1,3 jam untuk mengisi 1 kolam renang dengan 3 pompa A,B,C

1.3333333333333333

#### Geometric Mean

rata-rata yang dihitung dengan mengalikan semua data dalam suatu kelompok sampel, kemudian di akar pangkatkan dengan banyaknya data sampel tersebut. Biasanya digunakan pada perhitungan finansial (saham, aset, dll)

In [43]:
scipy.stats.gmean(x)

4.67788567485604

In [44]:
scipy.stats.gmean(y)

4.67788567485604

In [45]:
scipy.stats.gmean(z)

4.67788567485604

kasus geometric mean: <br>
Aset coca cola pada tahun 2018 = 1000 <br>
pada tahun 2019 berkembang 20%, -> 1.2<br>
pada tahun 2020 berkembang -30%, -> 0.7<br>
pada tahun 2021 berkembang 10%, -> 1.1<br>

In [112]:
(1.2*0.7*1.1)**(1/3)

0.9739963373377919

#### Median

Median merupakan elemen tengah dari kumpulan data yang telah disorting. Nilai median tidak terpengaruh pada kumpulan data yang memiliki outlier

In [51]:
statistics.median(x)

4

In [48]:
statistics.median_low(x[:-1])

2.5

In [49]:
statistics.median_high(x[:-1])

4

In [53]:
statistics.median(x[:-1])

3.25

In [52]:
median_ = np.median(y)
print(median_)

4.0


In [54]:
median_ = np.median(y[:-1])
print(median_)

3.25


#### Mode

Nilai yang paling sering muncul pada kumpulan data.

In [55]:
u = [2, 3, 2, 8, 12]
v = [12, 15, 12, 15, 21, 15, 12]

In [56]:
statistics.mode(u)

2

In [62]:
# statistics.mode(v) -> raise an error
scipy.stats.mode(v)

ModeResult(mode=array([12]), count=array([3]))

In [63]:
u, v, w = pd.Series(u), pd.Series(v), pd.Series([2, 2, math.nan])

In [65]:
# with pandas
print(u.mode())
print(v.mode())
print(w.mode())

0    2
dtype: int64
0    12
1    15
dtype: int64
0    2.0
dtype: float64


### Measures of Variability

Measures of central tendency tidak cukup untuk menggambarkan data. Kita juga memerlukan ukuran variabilitas yang mengukur penyebaran titik data

#### Variance

Sample variance menunjukkan secara numerik seberapa jauh titik data dari mean

In [66]:
var_ = statistics.variance(x)
var_

123.2

ddof = degrees of freedom -> kalo 1 berarti nanti di pembaginya n-1 (artinya unbiased)

In [67]:
var_ = np.var(y, ddof=1)
var_

123.19999999999999

In [68]:
# with pandas
var_ = y.var(ddof=1)
var_

123.19999999999999

#### Standard deviation

Sample standard deviation adalah cara lain mengukur penyebaran data. Berhubungan dengan varians sampel, karena standard deviation, 𝑠, adalah positive square root dari sample variance. standard deviation seringkali lebih cocok daripada varians karena memiliki satuan yang sama dengan data points. Manualnya setelah kita mendapatkan variance, kita dapat menghitung deviasi standar

In [69]:
std_ = statistics.stdev(x)
std_

11.099549540409287

In [70]:
np.std(y, ddof=1)

11.099549540409285

In [71]:
y.std(ddof=1)

11.099549540409285

#### Skewness

Sample skewness mengukur asimetri sampel data. Negative skewness menunjukkan bahwa ada ekor dominan di sisi kiri. Positive skewness menunjukkan ekor dominan di sisi kanan, Jika skewness mendekati 0 (misalnya antara −0.5 dan 0.5), maka dataset dianggap cukup simetris.

In [73]:
scipy.stats.skew(y, bias=False)

1.9470432273905927

In [74]:
z.skew()

1.9470432273905924

#### Percentiles

Tiap dataset memiliki tiga quartiles, yang merupakan persentil yang membagi dataset menjadi empat bagian
- First quartile adalah sampel persentil ke-25. Kuartil pertama membagi sekitar 25% item terkecil dari kumpulan data lainnya.
- Second quartile adalah sampel persentil ke-50 atau median. Kira-kira 25% item terletak di antara kuartil pertama dan kedua dan 25% lainnya antara kuartil kedua dan ketiga.
- Third quartile adalah sampel persentil ke-75. Kuartil ketiga membagi sekitar 25% item terbesar dari sisa kumpulan data.

In [90]:
y

[0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [92]:
len(y)

21

In [94]:
np.percentile(y, 5)

2.0

In [98]:
np.percentile(y, 90)

11.0

In [99]:
np.percentile(y, [25, 50, 75])

array([3., 5., 7.])

In [101]:
print(np.quantile(y, .25), np.quantile(y, .50), np.quantile(y, .75))

3.0 5.0 7.0


#### Ranges

In [88]:
y

[0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]

In [86]:
np.ptp(y)

14

In [89]:
x

[-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [87]:
np.ptp(x)

20

#### Covariance and Correlation Coefficient

Covariance <br>
ukuran yang mengukur kekuatan dan arah hubungan antara sepasang variabel
- If the correlation is positive, then the covariance is positive, as well. A stronger relationship corresponds to a higher value of the covariance.
- If the correlation is negative, then the covariance is negative, as well. A stronger relationship corresponds to a lower (or higher absolute) value of the covariance.
- If the correlation is weak, then the covariance is close to zero.

In [76]:
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)

In [77]:
cov_matrix = np.cov(x_, y_)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [79]:
cov_xy = x__.cov(y__)
cov_xy

19.95

Correlation coefficient, atau Pearson product-moment correlation coefficient, dilambangkan dengan simbol 𝑟. Coefficient  adalah ukuran lain dari korelasi antar data. 

- The value 𝑟 > 0 indicates positive correlation.
- The value 𝑟 < 0 indicates negative correlation.
- The value r = 1 is the maximum possible value of 𝑟. It corresponds to a perfect positive linear relationship between variables.
- The value r = −1 is the minimum possible value of 𝑟. It corresponds to a perfect negative linear relationship between variables.
- The value r ≈ 0, or when 𝑟 is around zero, means that the correlation between variables is weak

In [82]:
var_x = sum((item - np.mean(x))**2 for item in x) / ((len(x)) - 1)
var_y = sum((item - np.mean(y))**2 for item in y) / ((len(y)) - 1)
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [83]:
r, p = scipy.stats.pearsonr(x_, y_)

In [84]:
print(r, p)

0.861950005631606 5.122760847201171e-07


In [85]:
corr_matrix = np.corrcoef(x_, y_)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])